//! C# code generator from zennode schemas.
//!
//! Generates C# source files for imageflow-dotnet from the full node registry.
//! Uses zennode's rich schema metadata (types, ranges, defaults, labels,
//! sections, enum variants, KV keys) to produce:
//!
//! - **Node parameter classes** with properties, validation, and fluent setters
//! - **Enum definitions** with XML doc comments from variant descriptions
//! - **Querystring builder** that constructs validated RIAPI querystrings
//! - **Schema constants** for runtime key lookup

extern crate std;
use std::fmt::Write;
use std::string::String;
use std::vec::Vec;

use crate::schema_export;
use serde_json::Value;

/// Generated C# source files.
#[derive(Debug)]
pub struct CSharpOutput {
    /// (filename, content) pairs.
    pub files: Vec<(String, String)>,
}

/// Generate all C# source files from the full node registry.
pub fn generate() -> CSharpOutput {
    let schemas = schema_export::export_all();
    let mut files = Vec::new();

    // 1. Generate enum file from all enum parameters across nodes.
    let enums_cs = generate_enums(&schemas.node_schemas);
    if !enums_cs.is_empty() {
        files.push(("ZenEnums.g.cs".into(), enums_cs));
    }

    // 2. Generate node parameter classes.
    if let Some(defs) = schemas.node_schemas.get("$defs") {
        if let Some(defs_obj) = defs.as_object() {
            for (node_id, node_schema) in defs_obj {
                let class_name = node_id_to_class_name(node_id);
                let cs = generate_node_class(node_id, &class_name, node_schema);
                files.push((format!("{class_name}.g.cs"), cs));
            }
        }
    }

    // 3. Generate querystring builder.
    let qs_cs = generate_querystring_builder(&schemas.querystring_keys);
    files.push(("ZenQuerystring.g.cs".into(), qs_cs));

    CSharpOutput { files }
}

// ─── Node ID → C# class name ───

fn node_id_to_class_name(node_id: &str) -> String {
    // "zenresize.constrain" → "ZenresizeConstrain"
    // "zenjpeg.encode" → "ZenjpegEncode"
    node_id
        .split('.')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    format!("{upper}{}", chars.as_str())
                }
                None => String::new(),
            }
        })
        .collect()
}

fn csharp_type(schema: &Value, optional: bool) -> String {
    // Type can be a string ("integer") or array (["integer", "null"]) for optional params.
    let type_str = match schema.get("type") {
        Some(Value::String(s)) => s.as_str(),
        Some(Value::Array(arr)) => arr
            .iter()
            .filter_map(|v| v.as_str())
            .find(|s| *s != "null")
            .unwrap_or("string"),
        _ => "string",
    };

    let base = match type_str {
        "number" => "float",
        "integer" => {
            let min = schema.get("minimum").and_then(|v| v.as_i64()).unwrap_or(0);
            if min >= 0 {
                "uint"
            } else {
                "int"
            }
        }
        "boolean" => "bool",
        "string" => "string",
        "array" => "float[]",
        _ => "string",
    };

    if optional && base != "string" && base != "float[]" {
        format!("{base}?")
    } else {
        base.to_string()
    }
}

fn csharp_default(schema: &Value, cs_type: &str) -> Option<String> {
    let def = schema.get("default")?;
    match cs_type {
        "float" | "float?" => def.as_f64().map(|v| format!("{v}f")),
        "int" | "int?" => def.as_i64().map(|v| format!("{v}")),
        "uint" | "uint?" => def.as_u64().map(|v| format!("{v}")),
        "bool" | "bool?" => def.as_bool().map(|v| if v { "true".into() } else { "false".into() }),
        "string" => def.as_str().map(|s| format!("\"{s}\"")),
        _ => None,
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    format!("{upper}{}", chars.as_str())
                }
                None => String::new(),
            }
        })
        .collect()
}

// ─── Enum generation ───

fn generate_enums(node_schemas: &Value) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// <auto-generated/>");
    let _ = writeln!(out, "// Generated from zennode schemas. Do not edit.");
    let _ = writeln!(out, "namespace Imageflow.Zen;\n");

    let Some(defs) = node_schemas.get("$defs").and_then(|d| d.as_object()) else {
        return out;
    };

    let mut seen_enums = std::collections::HashSet::new();

    for (_node_id, schema) in defs {
        let Some(props) = schema.get("properties").and_then(|p| p.as_object()) else {
            continue;
        };
        for (param_name, param_schema) in props {
            let Some(variants) = param_schema.get("enum").and_then(|e| e.as_array()) else {
                continue;
            };
            let enum_name = pascal_case(param_name);
            if !seen_enums.insert(enum_name.clone()) {
                continue;
            }

            // Get enum labels for descriptions.
            let labels = param_schema
                .get("x-zennode-enum-labels")
                .and_then(|l| l.as_array());

            let _ = writeln!(out, "/// <summary>");
            if let Some(desc) = param_schema.get("description").and_then(|d| d.as_str()) {
                let _ = writeln!(out, "/// {desc}");
            } else if let Some(title) = param_schema.get("title").and_then(|t| t.as_str()) {
                let _ = writeln!(out, "/// {title}");
            }
            let _ = writeln!(out, "/// </summary>");
            let _ = writeln!(out, "public enum {enum_name}\n{{");

            for (i, variant) in variants.iter().enumerate() {
                let name = variant.as_str().unwrap_or("Unknown");
                let cs_name = pascal_case(name);

                // Look up description from labels.
                if let Some(labels) = labels {
                    if let Some(label_obj) = labels.get(i) {
                        if let Some(desc) = label_obj.get("description").and_then(|d| d.as_str()) {
                            if !desc.is_empty() {
                                let _ = writeln!(out, "    /// <summary>{desc}</summary>");
                            }
                        }
                    }
                }

                let _ = writeln!(out, "    {cs_name},");
            }

            let _ = writeln!(out, "}}\n");
        }
    }

    out
}

// ─── Node class generation ───

fn generate_node_class(node_id: &str, class_name: &str, schema: &Value) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// <auto-generated/>");
    let _ = writeln!(out, "// Generated from zennode schema: {node_id}");
    let _ = writeln!(out, "using System.Text.Json.Nodes;");
    let _ = writeln!(out, "namespace Imageflow.Zen;\n");

    // XML doc from schema.
    if let Some(desc) = schema.get("description").and_then(|d| d.as_str()) {
        let _ = writeln!(out, "/// <summary>");
        let _ = writeln!(out, "/// {desc}");
        let _ = writeln!(out, "/// </summary>");
    }

    let _ = writeln!(out, "public sealed class {class_name}\n{{");

    let Some(props) = schema.get("properties").and_then(|p| p.as_object()) else {
        let _ = writeln!(out, "}}");
        return out;
    };

    // Properties.
    for (param_name, param_schema) in props {
        let is_optional = param_schema
            .get("x-zennode-optional")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let cs_type = csharp_type(param_schema, is_optional);
        let cs_name = pascal_case(param_name);
        let default = csharp_default(param_schema, &cs_type);

        // XML doc.
        if let Some(title) = param_schema.get("title").and_then(|t| t.as_str()) {
            let _ = writeln!(out, "    /// <summary>{title}</summary>");
        }
        if let Some(unit) = param_schema.get("x-zennode-unit").and_then(|u| u.as_str()) {
            if !unit.is_empty() {
                let _ = writeln!(out, "    /// <remarks>Unit: {unit}</remarks>");
            }
        }

        // Property with default.
        if let Some(def) = default {
            let _ = writeln!(out, "    public {cs_type} {cs_name} {{ get; set; }} = {def};");
        } else {
            let _ = writeln!(out, "    public {cs_type} {cs_name} {{ get; set; }}");
        }
        let _ = writeln!(out);
    }

    // Fluent setters.
    for (param_name, param_schema) in props {
        let is_optional = param_schema
            .get("x-zennode-optional")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let cs_type = csharp_type(param_schema, is_optional);
        let cs_name = pascal_case(param_name);

        let _ = writeln!(
            out,
            "    public {class_name} Set{cs_name}({cs_type} value) {{ {cs_name} = value; return this; }}"
        );
    }

    let _ = writeln!(out);

    // ToJsonNode().
    let _ = writeln!(out, "    internal JsonNode ToJsonNode()");
    let _ = writeln!(out, "    {{");
    let _ = writeln!(out, "        var obj = new JsonObject();");
    for (param_name, param_schema) in props {
        let cs_name = pascal_case(param_name);
        let is_optional = param_schema
            .get("x-zennode-optional")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let cs_type = csharp_type(param_schema, is_optional);

        if is_optional || cs_type.ends_with('?') {
            let _ = writeln!(
                out,
                "        if ({cs_name} != null) obj.Add(\"{param_name}\", JsonValue.Create({cs_name}));"
            );
        } else if cs_type == "string" {
            let _ = writeln!(
                out,
                "        if (!string.IsNullOrEmpty({cs_name})) obj.Add(\"{param_name}\", {cs_name});"
            );
        } else {
            let _ = writeln!(
                out,
                "        obj.Add(\"{param_name}\", JsonValue.Create({cs_name}));"
            );
        }
    }
    let _ = writeln!(out, "        return obj;");
    let _ = writeln!(out, "    }}");

    let _ = writeln!(out, "}}");
    out
}

// ─── Querystring builder ───

fn generate_querystring_builder(qs_keys: &Value) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// <auto-generated/>");
    let _ = writeln!(out, "// Generated from zennode RIAPI key registry.");
    let _ = writeln!(out, "using System.Text;");
    let _ = writeln!(out, "namespace Imageflow.Zen;\n");
    let _ = writeln!(out, "/// <summary>");
    let _ = writeln!(
        out,
        "/// Fluent builder for RIAPI querystrings with compile-time key validation."
    );
    let _ = writeln!(out, "/// </summary>");
    let _ = writeln!(out, "public sealed class ZenQuerystring\n{{");
    let _ = writeln!(
        out,
        "    private readonly Dictionary<string, string> _params = new();\n"
    );

    // Typed setter methods from key registry.
    if let Some(nodes) = qs_keys.get("nodes").and_then(|n| n.as_object()) {
        for (_node_id, node_info) in nodes {
            let Some(keys) = node_info.get("keys").and_then(|k| k.as_array()) else {
                continue;
            };
            for key_info in keys {
                let Some(key) = key_info.get("key").and_then(|k| k.as_str()) else {
                    continue;
                };
                let label = key_info
                    .get("label")
                    .and_then(|l| l.as_str())
                    .unwrap_or(key);
                let desc = key_info
                    .get("description")
                    .and_then(|d| d.as_str())
                    .unwrap_or("");

                let value_schema = key_info.get("value_schema").unwrap_or(&Value::Null);
                let cs_param_type = match value_schema.get("type").and_then(|t| t.as_str()) {
                    Some("number") => "float",
                    Some("integer") => "int",
                    Some("boolean") => "bool",
                    _ => "string",
                };

                // Method name: sanitize key for C# identifier.
                let method_name = key_to_method_name(key);

                let _ = writeln!(out, "    /// <summary>{label}</summary>");
                if !desc.is_empty() {
                    let _ = writeln!(out, "    /// <remarks>{desc}</remarks>");
                }
                let _ = writeln!(
                    out,
                    "    public ZenQuerystring {method_name}({cs_param_type} value)"
                );
                let _ = writeln!(out, "    {{");
                if cs_param_type == "bool" {
                    let _ =
                        writeln!(out, "        _params[\"{key}\"] = value ? \"true\" : \"false\";");
                } else {
                    let _ = writeln!(
                        out,
                        "        _params[\"{key}\"] = value.ToString();",
                    );
                }
                let _ = writeln!(out, "        return this;");
                let _ = writeln!(out, "    }}\n");
            }
        }
    }

    // Build method.
    let _ = writeln!(out, "    /// <summary>Build the querystring.</summary>");
    let _ = writeln!(out, "    public string Build()");
    let _ = writeln!(out, "    {{");
    let _ = writeln!(out, "        if (_params.Count == 0) return \"\";");
    let _ = writeln!(out, "        var sb = new StringBuilder();");
    let _ = writeln!(out, "        var first = true;");
    let _ = writeln!(out, "        foreach (var (k, v) in _params)");
    let _ = writeln!(out, "        {{");
    let _ = writeln!(out, "            sb.Append(first ? '?' : '&');");
    let _ = writeln!(
        out,
        "            sb.Append(Uri.EscapeDataString(k));",
    );
    let _ = writeln!(out, "            sb.Append('=');");
    let _ = writeln!(
        out,
        "            sb.Append(Uri.EscapeDataString(v));",
    );
    let _ = writeln!(out, "            first = false;");
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "        return sb.ToString();");
    let _ = writeln!(out, "    }}\n");

    let _ = writeln!(out, "    public override string ToString() => Build();");
    let _ = writeln!(out, "}}");
    out
}

fn key_to_method_name(key: &str) -> String {
    // "jpeg.quality" → "JpegQuality"
    // "w" → "W"
    // "down.filter" → "DownFilter"
    // "accept.webp" → "AcceptWebp"
    // "f.sharpen" → "FSharpen"
    // "s.roundcorners" → "SRoundcorners"
    key.split(|c: char| c == '.' || c == '_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    format!("{upper}{}", chars.as_str())
                }
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn node_id_to_class_name_works() {
        assert_eq!(node_id_to_class_name("zenresize.constrain"), "ZenresizeConstrain");
        assert_eq!(node_id_to_class_name("zenjpeg.encode"), "ZenjpegEncode");
    }

    #[test]
    fn key_to_method_name_works() {
        assert_eq!(key_to_method_name("w"), "W");
        assert_eq!(key_to_method_name("jpeg.quality"), "JpegQuality");
        assert_eq!(key_to_method_name("down.filter"), "DownFilter");
        assert_eq!(key_to_method_name("accept.webp"), "AcceptWebp");
        assert_eq!(key_to_method_name("f.sharpen"), "FSharpen");
    }

    #[test]
    fn pascal_case_works() {
        assert_eq!(pascal_case("w"), "W");
        assert_eq!(pascal_case("down_filter"), "DownFilter");
        assert_eq!(pascal_case("scaling_colorspace"), "ScalingColorspace");
    }

    #[test]
    fn generate_produces_files() {
        let output = generate();
        assert!(!output.files.is_empty(), "should produce at least one file");

        // Should have ZenQuerystring.g.cs
        let qs_file = output
            .files
            .iter()
            .find(|(name, _)| name == "ZenQuerystring.g.cs");
        assert!(qs_file.is_some(), "should produce ZenQuerystring.g.cs");

        // Should have ZenEnums.g.cs
        let enums_file = output
            .files
            .iter()
            .find(|(name, _)| name == "ZenEnums.g.cs");
        assert!(enums_file.is_some(), "should produce ZenEnums.g.cs");
    }

    #[test]
    fn querystring_builder_has_w_method() {
        let output = generate();
        let (_, qs_content) = output
            .files
            .iter()
            .find(|(name, _)| name == "ZenQuerystring.g.cs")
            .unwrap();
        assert!(
            qs_content.contains("public ZenQuerystring W(int value)"),
            "should have W() method"
        );
    }

    #[test]
    fn querystring_builder_has_format_method() {
        let output = generate();
        let (_, qs_content) = output
            .files
            .iter()
            .find(|(name, _)| name == "ZenQuerystring.g.cs")
            .unwrap();
        assert!(
            qs_content.contains("public ZenQuerystring Format(string value)"),
            "should have Format() method"
        );
    }

    #[test]
    fn node_class_has_properties() {
        let output = generate();
        let constrain = output
            .files
            .iter()
            .find(|(name, _)| name.contains("Constrain"));
        assert!(constrain.is_some(), "should produce Constrain class");
        let (_, content) = constrain.unwrap();
        assert!(content.contains("public uint?"), "should have uint? properties");
        assert!(content.contains("ToJsonNode()"), "should have ToJsonNode()");
    }
}
